version: "3.9"
services:
  lbt_docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - ../.vscode:/code/lbt/.vscode
      - ../examples:/code/lbt/examples
      - ../include:/code/lbt/include
      - ../src:/code/lbt/src
      - ../test:/code/lbt/test
      - ../CMakeLists.txt:/code/lbt/CMakeLists.txt
      - ../Makefile:/code/lbt/Makefile
